--- #YAML:1.0
name:               Net-Frame-Layer-LLC
version:            1.02
abstract:           Logical-Link Control layer object
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:  0
    Net::Frame:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
